version: '3'
services:
  frontend:
    build: .
    ports:
      - "80:80"
    links:
      - backend

  backend:
    build: ./toystore
    links:
      - mongodb
    depends_on:
      - mongodb

  mongodb:
    image: mongo:3.0.15-wheezy
